#!/usr/bin/env python
import sys
import rospy
import rospkg
import yaml
from os.path import join
from tf import TransformBroadcaster
from robot_calibration import transformations


def run(source, target):
    key = source + "-" + target
    tfb = TransformBroadcaster()
    rate = rospy.Rate(50)

    rospack = rospkg.RosPack()
    conf_dir = join(rospack.get_path("robot_calibration"), "config")

    with open(join(conf_dir, "calibration_matrices.yml"), "r") as f:
        calib_matrices = yaml.load(f)
    
    while not rospy.is_shutdown():
        # Publish the calibration matrix
        transform = transformations.inverse_transform(calib_matrices[key])
        # transform = calib_matrices[key]
        tfb.sendTransform(transform[0], transform[1], rospy.Time.now(), target, source)
        rate.sleep()


if __name__ == '__main__':
    source = sys.argv[1]
    target = sys.argv[2]
    rospy.init_node('calibration_publisher', anonymous=True)
    run(source, target)