#!/usr/bin/env python
import rospy
from robot_calibration.calibration import Calibration


def main():
    robot_frame = rospy.get_param('robot_frame') # The world frame of the robot
    camera_frame = rospy.get_param('camera_frame') # The world frame of optitrack
    marker_frame = rospy.get_param('marker_frame') # The frame used for calibration in the optitrack's frame
    eef_frame = rospy.get_param('eef_frame') # The frame used for calibration in the robot's frame

    cal = Calibration(robot_frame, eef_frame, camera_frame, marker_frame)
    cal.calibrate()
    
if __name__ == '__main__':
    rospy.init_node('robot_calibration')
    main()