#!/usr/bin/env python
import rospy
from robot_calibration.recorder import Recorder


def main():
    joint_state_channel = rospy.get_param('joint_state_channel')
    rec = Recorder(joint_state_channel)
    new_recording = True

    while new_recording and not rospy.is_shutdown():
        rospy.loginfo("Please enter the name of the file to store the recording (do not put the path nor the extension)")
        savefile = raw_input()
        
        rospy.loginfo("Press enter to start recording")
        raw_input()
        rec.start_recording()

        rospy.loginfo("Recording... Press enter to stop recording")
        raw_input()
        filepath = rec.stop_recording()

        rospy.loginfo("Recorded data saved in " + filepath + ". Record a new demonstration? y/N")
        resp = raw_input()
        new_recording = (resp == "y") 

if __name__ == '__main__':
    rospy.init_node('recorder')
    main()